[[repos]]
repo = "builtin"

  [[repos.hooks]]
  id = "trailing-whitespace"

  [[repos.hooks]]
  id = "end-of-file-fixer"

  [[repos.hooks]]
  id = "pretty-format-json"
  args = [ "--autofix", "--indent=2" ]
  exclude = "^package-lock\\.json$"

[[repos]]
repo = "local"

  [[repos.hooks]]
  id = "npm-format"
  name = "NPM Format"
  entry = "npm run format"
  language = "system"
  pass_filenames = false

  [[repos.hooks]]
  id = "npm-check"
  name = "NPM Check"
  entry = "npm run check"
  language = "system"
  pass_filenames = false
